---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "192.168.94.97:5000/def/java-maven"
    insecure_registries: [ "192.168.94.97:5000" ]   

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/ci/build.sh
