---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "9952627133/java-maven"   

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/ci/build.sh
